### ISSUE TITLE
Having an issue with the rectangle meter and its "CornerRadius" feature

### ISSUE THREAD

**Issue by crafta** [khanhas/MagickMeter#2]
Hey

I recently got into this (amazing) plugin and I am currently working on a new skin. But now I have a (small) problem:
While using "CornerRadius" in a rectangle meter, I noticed that the edges do not round correctly.

Here is an example image of my problem:

![problem](https://user-images.githubusercontent.com/16546143/34450567-cf1a9cdc-ed0c-11e7-9b4e-3a67bb8a57cf.jpg)

I used the shape meter to create the darker rectangle and the plugin the create the pink rectangle behind. Both shapes use the same values.

Maybe you have a solution to this problem or its just a mistake on my side.

_If it helps, heres the code I used:_

`[MeasureBackground]`
`Measure=Plugin`
`Plugin=MagickMeter`
`Image = Rectangle 0,0,200,200,6 | Color 230,140,240,255`

**Comment by khanhas** [comment]
Thank you for pretty detail report, I'm really appreciate it.  

Actually there's no mistake here, drawing API Rainmeter used and ImageMagick are totally different things.  I used rectangle draw function directly from ImageMagick library, I didn't apply any trick or workaround.  

But I have to admit, it doesn't look right to me too. I also tried to draw it manually with 4 sides polygon which is basically drawn using Lines and Arcs. And it still has same result:

![image](https://user-images.githubusercontent.com/26436809/34466459-61be9232-ef06-11e7-85a9-a38cc6707843.png)

```ini
[MM]
Measure=Plugin
Plugin =MagickMeter
Image = Polygon 250,250,4,(300/sqrt(2)),(300/sqrt(2)),30,45 | Canvas 600,600 | Color FF0000
[Shape]
Meter = Shape
Shape = Rectangle 100,100,300,300,30 | Fill Color 00FF00 | StrokeWidth 0
```
So I think nothing I can do about that. If you've already decided to use MagickMeter, why not make the overlay in that too, isn't it easier?

**Comment by crafta** [comment]
Hey thank you for your response!

I think I will use Polygons from now on. I havent event thought about using Polygons to draw Rectangles, but they work pretty well for me. Thank your for this solution. 
Now I can continue working on my skin :)

_(Sorry its my first time using this plugin :P)_
