### ISSUE TITLE
Pixelation?

### ISSUE THREAD

**Issue by Sooperfish** [khanhas/MagickMeter#3]
I cannot find any pixelation effect, and resample and resize use interpolation so making the image smaller doesn't give me the right result. Is there any way to pixelate an image? 
If not, adding a pixelate or nearest neighbor resample effect might be useful in the future.

**Comment by Eldog02** [comment]
All you need to do is resize the image to the size you want, then use the [scale](https://github.com/khanhas/MagickMeter/wiki/Effects#scale) effect, scale it down to a small size, and then back to regular size. The scale effect doesn't antialias at all, so it produces a pixelated effect.
```
[MagickMeter]
Measure=Plugin
Plugin =MagickMeter
Image  =File (Whatever Image) | Resize 50,50 | Scale 25% | Scale 385%
DynamicVariables=1
```
![image](https://user-images.githubusercontent.com/34759177/42730860-be3cdeea-87ce-11e8-8587-c535cc01f505.png)

**Comment by Sooperfish** [comment]
Thanks! It works now.
